version: 2
updates:
  - package-ecosystem: docker-compose
    directories:
      - "**/*"
    schedule:
      interval: daily
    groups:
      all-docker-compose:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directories:
      - /
      - "**/*"
    schedule:
      interval: daily
    groups:
      all-github-actions:
        patterns:
          - "*"
