name: Get Semantic Version
description: Calculates a semantic version number based on git history.

inputs:
  workingDirectory:
    description: The directory to run the git commands in. Defaults to ./
    required: false
    default: ./
  skipCheckout:
    description: If true, do not run the checkout step. Defaults to false.
    required: false
    default: "false"
  writeSummary:
    description: Whether to write a summary to GitHub. Defaults to true.
    required: false
    default: "true"
outputs:
  branchName:
    description: The name of the branch being built.
    value: ${{ steps.version.outputs.branchName }}
  version:
    description: Full semantic version including suffix if not on master - {major}.{minor}.{patch}(-{branch}{increment}+{sha7})
    value: ${{ steps.version.outputs.semantic }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      if: ${{ inputs.skipCheckout != 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: ${{ inputs.workingDirectory }}

    # Add #major to the end of a commit message to increment the major version number
    # Add #minor to the end of a commit message to increment the minor version number
    - id: version
      name: Get semantic version
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
      env:
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      run: |
        source "${{ github.action_path }}/get-semantic-version.sh"

        # Export results
        echo "branchName=$branch_name" >> $GITHUB_OUTPUT
        echo "semantic=$semantic" >> $GITHUB_OUTPUT

    - name: Write summary to GitHub
      shell: bash
      run: |
        # Write output to GitHub Summary if requested
        if [ "${{ inputs.writeSummary }}" = "true" ]; then
            echo "# Branch" >> $GITHUB_STEP_SUMMARY
            echo "${{ steps.version.outputs.branchName }}" >> $GITHUB_STEP_SUMMARY
            echo "# Version" >> $GITHUB_STEP_SUMMARY
            echo "${{ steps.version.outputs.semantic }}" >> $GITHUB_STEP_SUMMARY
        fi
