# Requires GitHub Action:
# - GitTools@0.11.0 - https://github.com/marketplace/actions/gittools

name: Get Semantic Version
description: Calculates a semantic version number based on git history.

inputs:
  workingDirectory:
    description: The directory to run the git commands in. Defaults to ./
    required: false
    default: ./
  skipCheckout:
    description: If true, do not run the checkout step. Defaults to false
    required: false
    default: "false"
outputs:
  branchName:
    description: The name of the branch being built.
    value: ${{ steps.gitversion.outputs.BranchName }}
  version:
    description: Full semantic version including suffix if not on master - {major}.{minor}.{patch}(-{branch}{increment}+{sha7})
    value: ${{ steps.version.outputs.semantic }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      if: ${{ inputs.skipCheckout != 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: ${{ inputs.workingDirectory }}

    - id: semantic
      name: Calculate semantic version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        major_pattern: "#major"
        minor_pattern: "#minor"
        branch_pattern: ^main$|^master$

        # If not on main/master, include the branch name in version
        format: "${major}.${minor}.${patch}-${branch}.${increment}.${sha:0:7}"
        # On main/master branch, use a clean semver format
        main_format: "${major}.${minor}.${patch}"

    - id: version
      name: Get semantic version
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
      run: |
        semantic="${{ steps.semantic.outputs.version }}"

        # This is the value we propagate forward for any other consumers
        echo "Semantic version is: $semantic"
        echo "# Version" >> $GITHUB_STEP_SUMMARY
        echo "$semantic" >> $GITHUB_STEP_SUMMARY
        echo "semantic=$semantic" >> $GITHUB_OUTPUT
