services:
  actions-semantic-version-dev:
    container_name: actions-semantic-version-dev
    image: docker.io/spritelydev/base-devcontainer:0.2.3@sha256:8de341ef4885bba7e8f5c693269c0987d818f55788aa443cb11ad43624131c44
    privileged: true
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
