services:
  actions-semantic-version-dev:
    container_name: actions-semantic-version-dev
    image: docker.io/spritelydev/base-devcontainer:0.2.17@sha256:8acfe4039978de7863f463fb777825178ec0ba9f4425d89b00582ca473eaac45
    privileged: true
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
