services:
  actions-semantic-version-dev:
    container_name: actions-semantic-version-dev
    image: docker.io/spritelydev/base-devcontainer:0.2.77@sha256:31a5c1035e289ed7a7ab200d02782785fdb956798123649312f63a815e35683f
    privileged: true
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
