services:
  actions-semantic-version-dev:
    container_name: actions-semantic-version-dev
    build:
      dockerfile: Dockerfile
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
