services:
  actions-semantic-version-dev:
    container_name: actions-semantic-version-dev
    image: docker.io/spritelydev/dotnet8-devcontainer:0.3.0
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
