name: Build

on: [push, workflow_dispatch]

permissions:
  checks: write   # To be able to write test results
  contents: write # To be able to apply semantic version tags to the repository

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0

      - id: version
        name: Get semantic version
        uses: ./get

      - name: Create .env for build
        shell: bash
        run: |
          cat > ./.devcontainer/.env <<EOF
          EOF

      - name: Run tests
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6
        with:
          runCmd: |
            bats --report-formatter junit ./tests/
          push: never

      - name: Generate test report
        uses: dorny/test-reporter@b082adf0eced0765477756c2a610396589b8c637
        if: always()
        with:
          name: Test Results
          path: report.xml
          reporter: java-junit

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: ./apply
        with:
          version: ${{ steps.version.outputs.version }}
