name: Build

on: [push, workflow_dispatch]

permissions:
  contents: write # To be able to apply semantic version tags to the repository

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: version
        name: Get semantic version
        uses: ./get

      - name: Create .env for build
        shell: bash
        run: |
          cat > ./.devcontainer/.env <<EOF
          EOF

      - name: Run tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            bats --report-formatter junit ./tests/
          push: never

      - name: Generate test report
        uses: dorny/test-reporter@v1.9.1
        if: always()
        with:
          name: Test Results
          path: report.xml
          reporter: java-junit

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: ./apply
        with:
          version: ${{ steps.version.outputs.version }}
